# Generated by Django 6.0.7 on 2026-07-12 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fuel', '0001_initial'),
        ('trips', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuellog',
            name='Trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip'),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle'),
        ),
    ]
