# Generated by Django 6.0.7 on 2026-07-12 09:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('license_number', models.CharField(max_length=15)),
                ('license_category', models.CharField(max_length=50)),
                ('license_expiry', models.DateField()),
                ('phone', models.PositiveBigIntegerField()),
                ('safety_score', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On_Trip', 'On Trip'), ('Off_Duty', 'Off Duty'), ('Suspended', 'Suspended')])),
            ],
        ),
    ]
