# Generated by Django 6.0.7 on 2026-07-12 09:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_category', models.CharField(max_length=50)),
                ('license_expiry_date', models.DateField()),
                ('contact_number', models.CharField(max_length=20)),
                ('safety_score', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On_Trip', 'On Trip'), ('Off_Duty', 'Off Duty'), ('Suspended', 'Suspended')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
