# Generated by Django 6.0.7 on 2026-07-12 07:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('Fleet_Manager', 'Fleet Manager'), ('Dispatcher', 'Dispatcher'), ('Safety_Officer', 'Safety Officer'), ('Financial_Analyst', 'Financial Analyst')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
