# Generated by Django 6.0.7 on 2026-07-12 07:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('odometer', models.PositiveIntegerField()),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=13)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On_Trip', 'On Trip'), ('In_Shop', 'In Shop'), ('Retired', 'Retired')], default='Available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
