# Generated by Django 6.0.7 on 2026-07-12 09:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_id', models.CharField(max_length=100)),
                ('expense_type', models.CharField(choices=[('Tolls', 'Tolls'), ('Parking', 'Parking'), ('Food', 'Food'), ('Lodging', 'Lodging'), ('Repairs', 'Repairs')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
